version: '3.7'

services:
    db:
        image: mariadb:latest
        container_name: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: my_secret_pw
            MYSQL_DATABASE: test_db
            MYSQL_USER: devuser
            MYSQL_PASSWORD: devpass
        ports:
            - "3306:3306"
        volumes:
            - ./db_data:/var/lib/mysql
    web:
        container_name: php_web
        build:
            context: ./
            dockerfile: Dockerfile
        depends_on:
            - db
        links:
            - db:db_server
        ports:
            - "80:80"
        working_dir: /var/www/html/
        stdin_open: true
        tty: true
        volumes:
            - ./www:/var/www
            - ./db_data:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        depends_on:
            - db
        links:
            - db
        ports:
            - 8080:80
        environment:
            MYSQL_USER: devuser
            MYSQL_PASSWORD: devpass
            MYSQL_ROOT_PASSWORD: my_secret_pw
