version: '3.8'

services:
    composer:
        image: composer:latest
        container_name: composer
        environment:
            COMPOSER_HOME: /var/www
            COMPOSER_CACHE_DIR: \
        command:
            - install
        working_dir: /var/www
        volumes:
            - ./www:/var/www
    phpunit:
        image: php:latest
        restart: "no"
        volumes:
            - ./www:/var/www
        working_dir: /var/www
        entrypoint: vendor/bin/phpunit
    web:
        container_name: php_web
        build:
            context: ./
            dockerfile: Dockerfile
        depends_on:
            - composer
        ports:
            - "80:80"
        working_dir: /var/www/html/
        stdin_open: true
        tty: true
        volumes:
            - ./www:/var/www
            # - ./db_data:/var/lib/mysql
