version: '3.8'

services:
    composer:
        image: composer:latest
        container_name: composer
        environment:
            COMPOSER_HOME: /var/www
            COMPOSER_CACHE_DIR: \
        command:
            - install
            # - sh -c './vendor/bin/phpunit --version'
        working_dir: /var/www
        volumes:
            - ./www:/var/www
    web:
        container_name: php_web
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - "80:80"
        working_dir: /var/www/html/
        stdin_open: true
        tty: true
        volumes:
            - ./www:/var/www
            - ./db_data:/var/lib/mysql
